---
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
